### ISSUE TITLE
코드 블록 예쁘게 만들기

### ISSUE THREAD

**Issue by limjustin** [limjustin/jaeyoung-tech#1]
**1. 플러그인 설치**
```
npm install --save gatsby-transformer-remark gatsby-remark-highlight-code @deckdeckgo/highlight-code
```

**2. gatsby-config.js 파일 안에 플러그인 추가**
```yaml
// In your gatsby-config.js
plugins: [
  {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        {
          resolve: `gatsby-remark-highlight-code`,
          options: {
            terminal: "carbon",
            theme: "nord"
          }
        },
      ],
    },
  },
];
```
- single quote 표시가 아닌 **`** 표시이므로 주의!

**3. `src/layout/index.js` 파일에 코드 추가**
```javascript
import React from 'react';

...

import { defineCustomElements as deckDeckGoHighlightElement } from "@deckdeckgo/highlight-code/dist/loader";
deckDeckGoHighlightElement();

...

const Layout = ({ children }) => {
  const data = useStaticQuery(graphql`
```
- 중간에 잘 끼워넣으세요

**4. 세부 세팅 조절**
```css
deckgo-highlight-code {
  --deckgo-highlight-code-font-size: 1rem;
  --deckgo-highlight-code-padding: 0 0 0 2ch;
  --deckgo-highlight-code-font-family: 'Consolas', 'Monaco', monospace;
}
```
- `index.js` 파일과 같이 있는 `style.scss` 안에 오버라이딩
- 글자 크기, 들여쓰기 정도, 글꼴 등 수정 가능

**완성본**

<img width="85%" src="https://github.com/user-attachments/assets/9094ac97-5de8-4b1e-8b64-58b98ca24229"/>

---
**참고한 블로그**
- [[Gatsby] 코드 하이라이트 추가하기](https://velog.io/@hyeonzii/Gatsby-%EC%BD%94%EB%93%9C-%ED%95%98%EC%9D%B4%EB%9D%BC%EC%9D%B4%ED%8A%B8-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0)
- [How to set font size of code?](https://github.com/deckgo/gatsby-remark-highlight-code/issues/23)
- [terminal, theme 미리보기](https://docs.deckdeckgo.com/?path=/story/components-highlight-code--highlight-code&args=highlightLines:;lineNumbers:false;terminal:!undefined;theme:!undefined)
